In [2]:
import numpy as np
import pandas as pd
#from keras.datasets import fashion_mnist
#import matplotlib.pyplot as plt

In [ ]:
(X_train, Y_train) , (X_test, Y_test) = fashion_mnist.load_data()

In [ ]:
done = set()
fig, ax = plt.subplots(5, 2, figsize = (25, 25))
fig.tight_layout()
for x, y in zip(X_train, Y_train):
    if y not in done:
        done.add(y)
        ax[y % 5, y // 5].imshow(x)

In [31]:
class FNNClassifier:
    def __init__(self, N, L, activation='ReLU', optimizer='adam', weight_decay=0.0001, batch_size=200, learning_rate=0.001, num_epochs=200, weight_init='random'):
        self.activation = activation # 'identity', 'logistic', 'tanh', 'relu'
        self.optimizer = optimizer # 'normal', 'sgd', 'momentum', 'nesterov', 'rmsprop', 'adam', 'nadam'
        self.weight_decay = weight_decay # L2 regularization hyperparameter
        self.batch_size = batch_size # Batch size
        self.learning_rate = learning_rate # Learning Rate
        self.num_epochs = num_epochs # Number of epochs
        self.weight_init = weight_init # 'random', 'xavier'
        self.n = 100
        self.K = 10
        self.L = L
        self.N = N
        self.layer_sizes = np.zeros((L + 2))
        self.layer_sizes[1 : L + 1] = N
        self.W = []
        self.b = []
        self.a = []
        self.h = []
    
    def act(self, z):
        if(self.activation == 'sigmoid'):
            return 1 / (1 + np.exp(-z))
        elif(self.activation == 'tanh'):
            return np.tanh(z)
        elif(self.activation == 'ReLU'):
            return np.maximum(z, np.zeros(z.shape)) 
    
    def deriv_act(self, z):
        if(self.activation == 'sigmoid'):
            return 1 / (2 + np.exp(-z) + np.exp(z))
        elif(self.activation == 'tanh'):
            return np.cosh(z) ** -2
        elif(self.activation == 'ReLU'):
            return np.maximum(np.sign(z), np.zeros(z.shape))
    
    def oact(self, z):
        return np.exp(z) / np.exp(z).sum(axis=0)
    
    def forward_prop(self, X):
        self.a = [ np.zeros((1, 1))]
        self.h = [X]
        
        print('-------------------------a')
        for ii in self.a:
            print (ii)
        print('-------------------------h')
        for ii in self.h:
            print (ii)
        
        for i in range(1, self.L + 1):
            self.a.append( (self.b[i].T + (self.W[i].T @ self.h[i - 1]).T ).T)
            self.h.append(self.act(self.a[i]))
            print('-------------------------a')
            for ii in self.a:
                print (ii)
            print('-------------------------h')
            for ii in self.h:
                print (ii)
        self.h[-1] = self.oact(self.a[-1])
        return self.h[-1]
    
    def back_prop(self, Y_pred, ey):
        self.gradW, self.gradB, self.grada = [], [], []
        self.gradh = [ np.zeros((1, 1))]
        self.grada.append(-(ey - Y_pred))
        for i in range (self.L, 0, -1):
            self.gradW.append((self.grada[self.L - i] @ self.h[i - 1].T).T)
            self.gradB.append(self.grada[self.L - i].sum(axis=1))
            self.gradh.append(self.W[i] @ self.grada[self.L - i])
            self.grada.append( self.gradh[self.L - i + 1] * self.deriv_act(self.a[i - 1]))
        
        self.gradW.append(np.zeros((self.N, self.N)))
        self.gradB.append(np.zeros(self.N))
            
        return
    
    def wb_init(self, num):
        L = 10
        if(self.weight_init == 'random'):
            for i in range(self.L):
                self.W.append(0.1 + np.random.rand(self.N, self.N))
                self.b.append(0.1 + np.random.rand(self.N))
            self.W.append(0.1 + np.random.rand(self.N, self.K))
            self.W[1] = 0.1 + np.random.rand(num, self.W[1].shape[1])
            self.b.append(0.1 + np.random.rand(self.K))
            
        '''
        elif self.weight_init == 'Xavier':
# example of the xavier weight initialization
from math import sqrt
from numpy import mean
from numpy.random import rand
# number of nodes in the previous layer
n = 10
# calculate the range for the weights
lower, upper = -(1.0 / sqrt(n)), (1.0 / sqrt(n))
# generate random numbers
numbers = rand(1000)
# scale to the desired range
scaled = lower + numbers * (upper - lower)
# summarize
print(lower, upper)
print(scaled.min(), scaled.max())
print(scaled.mean(), scaled.std())
        '''
    
    def grad_desc(self, X, Y):
        
        self.wb_init(X.shape[0])
        
        print('-------------------------w')
        for ii in self.W:
            print (ii)
        print('-------------------------b')
        for ii in self.b:
            print (ii)
        
        update_W, update_b = self.W, self.b
        v_W, v_b = self.W, self.b
        m_W, m_b = self.W, self.b
        
        ey = np.zeros((self.K, self.n))
        rows = np.arange(self.n)
        ey[Y.T - 1, rows] = 1
        
        for t in range(1, self.num_epochs + 1):
            
            if(self.optimizer == 'sgd'):
                for tt in range(0, ((self.n + self.batch_size - 1) // self.batch_size)):
                    idx = np.random.randint(self.n, size = self.batch_size)
                    ey = np.zeros((self.K, self.batch_size))
                    rows = np.arange(self.batch_size)
                    ey[Y.T[idx] - 1, rows] = 1
                    Y_pred = self.forward_prop(X.T[idx, :].T)

                    self.back_prop(Y_pred, ey)
                    dW = self.gradW[::-1]
                    db = self.gradB[::-1]

                    update_W = [self.learning_rate * u for u in dW]
                    update_b = [self.learning_rate * u for u in db]
                    update_W = [u + v * self.weight_decay for u, v in zip(update_W, dW)]
                    self.W = [u - v for u, v in zip(self.W, update_W)]
                    self.b = [u - v for u, v in zip(self.b, update_b)]
                continue
                
            Y_pred = self.forward_prop(X)
            
            print('-------------------------a')
            for ii in self.a:
                print (ii)
            print('-------------------------h')
            for ii in self.h:
                print (ii)
            
            if(self.optimizer == 'nesterov'):
                W , b = self.W, self.b
                ngamma = 0.9 # Hyperparameter
                self.W = [u - ngamma * v for u, v in zip(self.W, update_W)]
                self.b = [u - ngamma * v for u, v in zip(self.b, update_b)]
            
            self.back_prop(Y_pred, ey)
            
            
            
            dW = self.gradW[::-1]
            db = self.gradB[::-1]
            
            if(self.optimizer == 'normal'):
                update_W = [self.learning_rate * u for u in dW]
                update_b = [self.learning_rate * u for u in db]

                
            elif(self.optimizer == 'momentum'):
                mgamma = 0.9 # Hyperparameter
                update_W = [mgamma * u + self.learning_rate * v for u, v in zip(update_W, dW)]
                update_b = [mgamma * u + self.learning_rate * v for u, v in zip(update_b, db)]
            
            elif(self.optimizer == 'nesterov'):
                self.W, self.b = W, b
                update_W = [ngamma * u + self.learning_rate * v for u, v in zip(update_W, dW)]
                update_b = [ngamma * u + self.learning_rate * v for u, v in zip(update_b, db)]
            
            elif(self.optimizer == 'rmsprop'):
                rbeta = 0.9
                epsilon = 0.1
                v_W = [rbeta * u + (1 - rbeta) * (v ** 2) for u, v in zip(v_W, dW)]
                v_b = [rbeta * u + (1 - rbeta) * (v ** 2) for u, v in zip(v_b, db)]
                update_W = [(self.learning_rate * u) / np.sqrt(v + epsilon) for u, v in zip(dW, v_W)]
                update_b = [(self.learning_rate * u) / np.sqrt(v + epsilon) for u, v in zip(db, v_b)]
                
            elif(self.optimizer == 'adam'):
                abeta1 = 0.99
                abeta2 = 0.999
                epsilon = 0.1
                m_W = [abeta1 * u + (1 - abeta1) * v for u, v in zip(m_W, dW)]
                m_b = [abeta1 * u + (1 - abeta1) * v for u, v in zip(m_b, db)]
                v_W = [abeta2 * u + (1 - abeta2) * (v ** 2) for u, v in zip(v_W, dW)]
                v_b = [abeta2 * u + (1 - abeta2) * (v ** 2) for u, v in zip(v_b, db)]
                update_W = [( (self.learning_rate * u) / (1 - abeta1 ** t) ) / np.sqrt( (v / (1 - abeta2 ** t)) + epsilon) for u, v in zip(m_W, v_W)]
                update_b = [( (self.learning_rate * u) / (1 - abeta1 ** t) ) / np.sqrt( (v / (1 - abeta2 ** t)) + epsilon) for u, v in zip(m_b, v_b)]
                 
            elif(self.optimizer == 'nadam'):
                nbeta1 = 0.99
                nbeta2 = 0.999
                epsilon = 0.1
                m_W = [nbeta1 * u + (1 - nbeta1) * v for u, v in zip(m_W, dW)]
                m_b = [nbeta1 * u + (1 - nbeta1) * v for u, v in zip(m_b, db)]
                v_W = [nbeta2 * u + (1 - nbeta2) * (v ** 2) for u, v in zip(v_W, dW)]
                v_b = [nbeta2 * u + (1 - nbeta2) * (v ** 2) for u, v in zip(v_b, db)]
                update_W = [(self.learning_rate * (nbeta1 * u + (1 - nbeta1) * v)) / (1 - nbeta1 ** t) for u, v in zip(m_W, dW)]
                update_W = [ (u) / np.sqrt( (v / (1 - nbeta2 ** t)) + epsilon) for u, v in zip(m_W, v_W)]
                update_b = [(self.learning_rate * (nbeta1 * u + (1 - nbeta1) * v)) / (1 - nbeta1 ** t) for u, v in zip(m_b, db)]
                update_b = [ (u) / np.sqrt( (v / (1 - nbeta2 ** t)) + epsilon) for u, v in zip(m_b, v_b)]
            
            
            update_W = [u + v * self.weight_decay for u, v in zip(update_W, dW)]
            
            self.W = [u - v for u, v in zip(self.W, update_W)]
            self.b = [u - v for u, v in zip(self.b, update_b)]
    
    def fit(self, X_train, Y_train):
        self.n = X_train.shape[0]
        self.batch_size = min(self.batch_size, self.n)
        K = np.max(Y_train) # Y_train must have values from 1 to K
        self.layer_sizes[self.L - 1] = K
        self.K = K
        self.grad_desc(X_train.T, Y_train.T)
        
    def predict_proba(self, X_test):
        return self.forward_prop(X_test.T).T

In [32]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
X.shape, y.shape

((150, 4), (150,))

In [34]:
X = np.array([[ 1.,  2.,  0.,  8.],
 [ 6.,  3., 10.,  5.],
 [ 5.,  2.,  9.,  4.],
 [ 5.,  6.,  3.,  9.],
 [ 4.,  9.,  5.,  5.],
 [ 4.,  5.,  2.,  1.],
 [ 8.,  2.,  8.,  0.],
 [ 3.,  3.,  7.,  6.],
 [ 4.,  6.,  3.,  6.],
 [ 7.,  8.,  2.,  2.],
 [ 5.,  5., 10.,  2.],
 [ 3.,  7.,  8.,  7.],
 [ 2.,  5.,  3.,  2.],
 [ 0.,  5.,  2.,  3.],
 [ 7.,  0.,  6.,  8.]])
y = np.array([3, 6, 5, 6, 6, 3, 4, 5, 5, 5, 6, 6, 3, 2, 5])
model = FNNClassifier(1, 2, activation = 'ReLU', optimizer = 'normal', batch_size = 25, num_epochs = 4)
model.fit(X, y)
model.predict_proba(X)

-------------------------w
[[0.92983818]]
[[1.07480494]
 [0.92030914]
 [0.14502453]
 [0.82910664]]
[[0.99570385 1.03776273 0.31020157 0.17683569 0.85458726 0.40766475]]
-------------------------b
[0.30574932]
[0.26372277]
[0.80830638 0.14644208 0.82308202 0.13110572 0.62913134 0.25154553]
-------------------------a
[[0.]]
-------------------------h
[[ 1.  6.  5.  5.  4.  4.  8.  3.  4.  7.  5.  3.  2.  0.  7.]
 [ 2.  3.  2.  6.  9.  5.  2.  3.  6.  8.  5.  7.  5.  5.  0.]
 [ 0. 10.  9.  3.  5.  2.  8.  7.  3.  2. 10.  8.  3.  2.  6.]
 [ 8.  5.  4.  9.  5.  1.  0.  6.  6.  2.  2.  7.  2.  3.  8.]]
-------------------------a
[[0.]]
[[ 9.81199909 15.06925828 12.10001304 19.05663562 17.71638061 10.28364392
  11.86297677 12.23887652 15.49451077 17.09809279 13.34775171 16.89424425
   9.10816521  7.64263744 15.29035759]]
-------------------------h
[[ 1.  6.  5.  5.  4.  4.  8.  3.  4.  7.  5.  3.  2.  0.  7.]
 [ 2.  3.  2.  6.  9.  5.  2.  3.  6.  8.  5.  7.  5.  5.  0.]
 [ 0. 10.  9.  3.  5.

array([[2.21340696e-01, 2.02752635e-01, 1.42511427e-02, 1.12583029e-03,
        4.33084354e-01, 1.27445341e-01],
       [1.78268146e-01, 2.10661621e-01, 3.30443655e-03, 1.14839550e-04,
        5.06496297e-01, 1.01154660e-01],
       [2.06613285e-01, 2.06498111e-01, 8.68724160e-03, 5.18151431e-04,
        4.59311588e-01, 1.18371623e-01],
       [1.36665446e-01, 2.11175786e-01, 6.82703259e-04, 9.99261010e-06,
        5.75102988e-01, 7.63630833e-02],
       [1.49947988e-01, 2.11719403e-01, 1.16411777e-03, 2.27889914e-05,
        5.52925926e-01, 8.42197758e-02],
       [2.18219975e-01, 2.03664308e-01, 1.28235137e-02, 9.53815597e-04,
        4.38824652e-01, 1.25513736e-01],
       [2.07542343e-01, 2.06299861e-01, 8.96181772e-03, 5.43999373e-04,
        4.57710893e-01, 1.18941086e-01],
       [2.03718739e-01, 2.07087229e-01, 7.88404243e-03, 4.45223779e-04,
        4.64265048e-01, 1.16599718e-01],
       [1.68345124e-01, 2.11367592e-01, 2.32013440e-03, 6.63167893e-05,
        5.22708679e-01, 

In [ ]:
import wandb

sweep_config = {
    'method' : 'random',
    'metric' : {
        'name' : 'accuracy',
        'goal' : 'maximize'
    },
    'parameters' : {
        'N' : [32, 64, 128],
        'L' : [3, 4, 5],
        'activation' : ['sigmoid', 'tanh', 'ReLU'],
        'optimizer' : ['sgd', 'momentum', 'nesterov', 'rmsprop', 'adam', 'nadam'],
        'weight_decay' : [0, 0.0005, 0.5],
        'batch_size' : [16, 32, 64],
        'num_epochs' : [5, 10],
        'learning_rate' : [0.001, 0.0001],
        'weight_init' : ['random', 'Xavier']
    }
}

In [ ]:
sweep_id = wandb.sweep(sweep_config, entity = 'sweep', project = 'cs6910a12021')

In [ ]:
def train():
    def_params = {
        'N' : 32,
        'L' : 4,
        'activation' : 'ReLU',
        'optimizer' : 'adam',
        'weight_decay' : 0.0005,
        'batch_size' : 32,
        'num_epochs' : 5,
        'learning_rate' : 0.001,
        'weight_init' : 'random'
    }
    wandb.init(config = def_params)
    config = wandb.config
    model = FFNClassifier(**config)
    model.fit(X_train, Y_train)
    

In [ ]:
wandb.agent(sweep_id, train)